version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bd
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data 

  api:
    image: python:3.10-slim
    container_name: api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command: bash -c "apt-get update && apt-get install -y libpq-dev gcc && pip install --no-cache-dir -r /app/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./api/.env
      
volumes:
  pgdata:
